### PR TITLE
Change syntax for getting 0th column

### PR DESCRIPTION
**Pull request by milantru**
In my solution I had to modify this part because for some reason it didn't work for me... It seemed that the problem was slicing (e.g. train_data[:,0]), maybe it doesn't work with my python version (my python version is 3.10.7). Either way, I thought that if because of this change the code can be run on newer versions and also on the older versions then maybe it would be better this way. It is still a small piece of code thanks to python comprehensions. I know it's only a small change, but it might save someone a few seconds.

### CODE REVIEW

**Comment by foxik** [comment]
Hi,

thanks for the message!

We will be using the syntax `[:, something]` quite a lot in the future too, which is the reason I do not want to merge this.

The reason why it doesn't work for you is that this syntax works only for numpy arrays. And while in your code the `features` are a numpy array since `order==2`, when `order==1` the `features` are just a list of lists -- and then it stops working. But if you pass the initial values of `features` through `np.array`, it will convert it from a list of lists to a numpy array and the plotting code will work without change.

**Comment by milantru** [comment]
Oh, I see. Thank you for the explanation.

**Comment by foxik** [comment]
You are welcome.

In the end I updated the comment above the plotting code to state that the data must be in numpy arrays, see commit ff1a834240ca84e76b9b48cf74140e8b8df5f650, so that if an error occurs, it might be easier for the students to find out why. This earns you a community-work point ;-)

Cheers.

**Comment by milantru** [comment]
Thank you very much! :-D

**Pull request closed without merging**
