### PR TITLE
fixed some mistakes in lecture 12

### PR DESCRIPTION
**Pull request by dunzel**

### CODE REVIEW

**Comment by dunzel** [comment]
By the way, I think I should also include my Recodex ID if you think I deserve some community points :D

`ba6a23c5-a008-4a1c-a4e6-046db74f6fdf`

**Comment by foxik** [comment]
Thanks, merging, and incrementing your community-work point counter. Thanks for the ID (BTW, I was able to identify where to put points even without it).

**Comment by dunzel** [comment]
@foxik I am curious, how did you identify me? 🕵️ 😄

**Comment by foxik** [comment]
Moving the conversation to Piazza.

**Pull request merged**
